version: '3.8'
services:
        nginx:
                image: nginx:1
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf
                depends_on:
                        - backend
                        - frontend
                ports:
                        - 80:80
                environment:
                        - NGINX_HOST=http://localhost
                        - NGINX_PORT=80
        redis:
                image: redis:alpine
                volumes:
                        - ./redis:/data
        backend:
                image: 3.6-backend
                build:
                        context: .
                        dockerfile: Dockerfile.backend
                ports:
                        - 8080:8080
                environment:
                        - REDIS_HOST=redis
                        - POSTGRES_HOST=db
                        - POSTGRES_USER=example
                        - POSTGRES_PASSWORD=example
                        - POSTGRES_DATABASE=example
                depends_on:
                        - redis
                        - db
        frontend:
                image: 3.6-frontend
                build:
                        context: .
                        dockerfile: Dockerfile.frontend
                ports:
                        - 5000:5000
                depends_on:
                        - backend
        db:
                image: postgres:13.2-alpine
                restart: unless-stopped
                volumes:
                        - ./postgre:/var/lib/postgresql/data
                environment:
                        - POSTGRES_PASSWORD=example
                        - POSTGRES_USER=example
                        - POSTGRES_DB=example
