FROM golang:1-alpine as build-stage
WORKDIR /usr/src/app
COPY ./example-backend .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo

FROM scratch
WORKDIR /usr/src/app
ENV PORT=8080
ENV REQUEST_ORIGIN=http://localhost
EXPOSE 8080
COPY --from=build-stage /usr/src/app/server /usr/src/app/server
CMD ["./server"]