version: '3.8'
services:
        redis:
                image: redis:alpine
        backend:
                image: backend
                build:
                        context: .
                        dockerfile: Dockerfile.backend
                ports:
                        - 8080:8080
                environment:
                        - REDIS_HOST=redis
        frontend:
                image: frontend
                build:
                        context: .
                        dockerfile: Dockerfile.frontend
                ports:
                        - 5000:5000
